name: Managed CI On Merge
on:
  release:
    types: [released]
  push:
    branches:
      - main
      - master
      - mainline
    paths-ignore:
      - '.github/**'
jobs:
  mci-pre-lint:
    uses: ./.github/workflows/mci-pre-lint.yaml
    secrets: inherit
  mci-lint:
    uses: glcp/managed-ci-workflow/.github/workflows/mci-lint.yaml@main
    secrets: inherit
    needs: mci-pre-lint
  mci-pre-test:
    uses: ./.github/workflows/mci-pre-test.yaml
    secrets: inherit
  mci-unit-test:
    uses: glcp/managed-ci-workflow/.github/workflows/mci-unit-test.yaml@main
    secrets: inherit
    needs: mci-pre-test
  build:
    uses: glcp/managed-ci-workflow/.github/workflows/mci-build.yaml@main
    secrets: inherit
    needs: [mci-lint, mci-unit-test]
  post-build:
    uses: glcp/managed-ci-workflow/.github/workflows/mci-post-build.yaml@main
    secrets: inherit
    needs: build
  mci-custom-final:
    uses: ./.github/workflows/mci-custom-final.yaml
    secrets: inherit
    needs: post-build
  mci-metrics:
    if: always()
    uses: glcp/managed-ci-workflow/.github/workflows/mci-metrics.yaml@main
    secrets: inherit
    needs: mci-custom-final
